[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-cache-core"

[plugins.inputs]
  paths = ["node_modules", "package-lock.json"]
